"""演示用样本。坐标落在火星常见滑坡区（Valles Marineris、撞击坑壁、高纬），
不是写死的地球假点。滕佳杰清洗入库后可用真实编目覆盖。
"""

SEED_LANDSLIDES = [
    {
        "id": "ls_0001",
        "name": "Ius Chasma west wall",
        "type": "slump",
        "lat": -7.2,
        "lon": -85.4,
        "length_m": 18500,
        "width_m": 9200,
        "slope_deg": 22.0,
        "mission": "MRO",
        "region": "Valles Marineris",
        "features": ["chasma wall", "layered deposit"],
        "description": "Ius Chasma 西壁大型滑塌，可见多级台阶与坡脚堆积。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0002",
        "name": "Coprates Chasma north scarp",
        "type": "slide",
        "lat": -13.4,
        "lon": -61.8,
        "length_m": 24200,
        "width_m": 11000,
        "slope_deg": 19.5,
        "mission": "MRO",
        "region": "Valles Marineris",
        "features": ["chasma wall"],
        "description": "Coprates 北壁长程滑动，舌状前缘覆盖谷底。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0003",
        "name": "Ganges Chasma slump complex",
        "type": "slump",
        "lat": -7.9,
        "lon": -48.6,
        "length_m": 9800,
        "width_m": 5400,
        "slope_deg": 24.0,
        "mission": "MRO",
        "region": "Valles Marineris",
        "features": ["chasma wall", "light-toned layer"],
        "description": "Ganges Chasma 滑塌组合，层状物质沿坡解体。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0004",
        "name": "Juventae Chasma hanging wall",
        "type": "fall",
        "lat": -4.3,
        "lon": -61.2,
        "length_m": 2100,
        "width_m": 800,
        "slope_deg": 38.0,
        "mission": "MRO",
        "region": "Valles Marineris",
        "features": ["steep scarp"],
        "description": "陡崖崩落，坡脚见块石堆。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0005",
        "name": "Capri Chasma debris tongue",
        "type": "flow",
        "lat": -13.8,
        "lon": -47.1,
        "length_m": 15600,
        "width_m": 3200,
        "slope_deg": 12.0,
        "mission": "MGS",
        "region": "Valles Marineris",
        "features": ["debris apron"],
        "description": "碎屑流舌沿谷底延伸，表面有流线。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0006",
        "name": "Eos Chasma south terrace",
        "type": "slide",
        "lat": -16.2,
        "lon": -43.5,
        "length_m": 20100,
        "width_m": 8700,
        "slope_deg": 16.5,
        "mission": "MRO",
        "region": "Valles Marineris",
        "features": ["terrace", "chasma wall"],
        "description": "Eos 南壁滑动，保留较完整的原始层理。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0007",
        "name": "Candor Chasma interior deposit",
        "type": "slump",
        "lat": -6.5,
        "lon": -71.0,
        "length_m": 6400,
        "width_m": 4100,
        "slope_deg": 18.0,
        "mission": "MRO",
        "region": "Valles Marineris",
        "features": ["interior layered deposit"],
        "description": "谷内层状沉积物局部滑塌。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0008",
        "name": "Ophir Chasma headscarp",
        "type": "slump",
        "lat": -4.0,
        "lon": -72.5,
        "length_m": 11200,
        "width_m": 6300,
        "slope_deg": 21.0,
        "mission": "Viking",
        "region": "Valles Marineris",
        "features": ["headscarp"],
        "description": "Ophir 后缘陡坎清晰，为早期 Viking 影像中的典型滑坡。",
        "source_url": "https://pds.nasa.gov/",
    },
    {
        "id": "ls_0009",
        "name": "Melas Chasma western wall",
        "type": "slide",
        "lat": -10.1,
        "lon": -74.8,
        "length_m": 17800,
        "width_m": 7600,
        "slope_deg": 17.0,
        "mission": "MRO",
        "region": "Valles Marineris",
        "features": ["chasma wall"],
        "description": "Melas 西壁大型滑坡，体积大、运移距离长。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0010",
        "name": "Tithonium Chasma collapse",
        "type": "fall",
        "lat": -4.8,
        "lon": -86.1,
        "length_m": 1500,
        "width_m": 600,
        "slope_deg": 41.0,
        "mission": "MRO",
        "region": "Valles Marineris",
        "features": ["steep scarp", "talus"],
        "description": "Tithonium 陡壁崩塌，碎石锥发育。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0011",
        "name": "Hebes Chasma isolated slump",
        "type": "slump",
        "lat": -1.1,
        "lon": -76.2,
        "length_m": 7300,
        "width_m": 3900,
        "slope_deg": 20.5,
        "mission": "MRO",
        "region": "Valles Marineris",
        "features": ["closed chasma"],
        "description": "封闭峡谷 Hebes 内壁滑塌。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0012",
        "name": "Echus Chasma plateau edge",
        "type": "slide",
        "lat": 0.8,
        "lon": -80.4,
        "length_m": 5400,
        "width_m": 2800,
        "slope_deg": 15.0,
        "mission": "MGS",
        "region": "Valles Marineris",
        "features": ["plateau edge"],
        "description": "高原边缘向 Echus 滑动。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0013",
        "name": "Noctis Labyrinthus graben wall",
        "type": "fall",
        "lat": -7.0,
        "lon": -102.3,
        "length_m": 900,
        "width_m": 350,
        "slope_deg": 36.0,
        "mission": "MRO",
        "region": "Noctis Labyrinthus",
        "features": ["graben"],
        "description": "迷宫状地堑壁局部崩落。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0014",
        "name": "Noctis junction slump",
        "type": "slump",
        "lat": -6.4,
        "lon": -99.7,
        "length_m": 3200,
        "width_m": 1800,
        "slope_deg": 23.0,
        "mission": "MRO",
        "region": "Noctis Labyrinthus",
        "features": ["graben", "junction"],
        "description": "地堑交汇处滑塌。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0015",
        "name": "Olympus Mons eastern scarp",
        "type": "slide",
        "lat": 18.4,
        "lon": -132.0,
        "length_m": 31000,
        "width_m": 14000,
        "slope_deg": 14.0,
        "mission": "Viking",
        "region": "Tharsis",
        "features": ["volcano scarp", "aureole"],
        "description": "奥林匹斯盾状火山东缘大型滑动，与光环沉积相关。",
        "source_url": "https://pds.nasa.gov/",
    },
    {
        "id": "ls_0016",
        "name": "Olympus aureole lobe",
        "type": "flow",
        "lat": 22.1,
        "lon": -135.6,
        "length_m": 45000,
        "width_m": 18000,
        "slope_deg": 6.5,
        "mission": "MGS",
        "region": "Tharsis",
        "features": ["aureole"],
        "description": "火山光环叶状体，解释为远程碎屑流。",
        "source_url": "https://pds.nasa.gov/",
    },
    {
        "id": "ls_0017",
        "name": "Ascraeus Mons flank slump",
        "type": "slump",
        "lat": 11.3,
        "lon": -104.5,
        "length_m": 8900,
        "width_m": 4700,
        "slope_deg": 18.5,
        "mission": "MRO",
        "region": "Tharsis",
        "features": ["volcano flank"],
        "description": "阿斯克劳斯火山侧翼滑塌。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0018",
        "name": "Pavonis Mons caldera wall",
        "type": "fall",
        "lat": 0.8,
        "lon": -113.4,
        "length_m": 1200,
        "width_m": 500,
        "slope_deg": 33.0,
        "mission": "MRO",
        "region": "Tharsis",
        "features": ["caldera"],
        "description": "孔雀座火山口壁崩落。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0019",
        "name": "Arsia Mons western slide",
        "type": "slide",
        "lat": -9.2,
        "lon": -121.0,
        "length_m": 16500,
        "width_m": 7200,
        "slope_deg": 13.5,
        "mission": "MGS",
        "region": "Tharsis",
        "features": ["volcano flank"],
        "description": "阿尔西亚火山西坡滑动。",
        "source_url": "https://pds.nasa.gov/",
    },
    {
        "id": "ls_0020",
        "name": "Alba Mons northern apron",
        "type": "flow",
        "lat": 41.0,
        "lon": -109.5,
        "length_m": 22000,
        "width_m": 9000,
        "slope_deg": 8.0,
        "mission": "MRO",
        "region": "Tharsis",
        "features": ["volcano apron"],
        "description": "阿尔巴火山北缘缓坡碎屑流。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0021",
        "name": "Hale crater wall slump",
        "type": "slump",
        "lat": -35.7,
        "lon": -36.4,
        "length_m": 4100,
        "width_m": 2300,
        "slope_deg": 26.0,
        "mission": "MRO",
        "region": "Argyre rim",
        "features": ["crater wall"],
        "description": "Hale 撞击坑内壁滑塌，HiRISE 常见目标。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0022",
        "name": "Bond crater northern wall",
        "type": "slide",
        "lat": -33.1,
        "lon": -36.0,
        "length_m": 5600,
        "width_m": 2500,
        "slope_deg": 21.0,
        "mission": "MRO",
        "region": "Argyre rim",
        "features": ["crater wall"],
        "description": "Bond 坑北壁滑动。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0023",
        "name": "Argyre basin scarp fall",
        "type": "fall",
        "lat": -49.7,
        "lon": -43.2,
        "length_m": 1800,
        "width_m": 700,
        "slope_deg": 34.0,
        "mission": "MGS",
        "region": "Argyre",
        "features": ["basin scarp"],
        "description": "阿尔及尔盆地边缘崩落。",
        "source_url": "https://pds.nasa.gov/",
    },
    {
        "id": "ls_0024",
        "name": "Holden crater terrace slump",
        "type": "slump",
        "lat": -26.4,
        "lon": -34.0,
        "length_m": 6700,
        "width_m": 3100,
        "slope_deg": 19.0,
        "mission": "MRO",
        "region": "Uzboi-Holden",
        "features": ["crater wall", "terrace"],
        "description": "Holden 坑阶地滑塌。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0025",
        "name": "Eberswalde delta scarp",
        "type": "slide",
        "lat": -24.0,
        "lon": -33.3,
        "length_m": 2400,
        "width_m": 1100,
        "slope_deg": 16.0,
        "mission": "MRO",
        "region": "Uzboi-Holden",
        "features": ["delta", "crater wall"],
        "description": "Eberswalde 三角洲前缘小型滑动。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0026",
        "name": "Gale crater north wall",
        "type": "slump",
        "lat": -4.6,
        "lon": 137.4,
        "length_m": 5200,
        "width_m": 2700,
        "slope_deg": 25.0,
        "mission": "MRO",
        "region": "Aeolis",
        "features": ["crater wall"],
        "description": "盖尔撞击坑北壁滑塌，Curiosity 着陆区外围。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0027",
        "name": "Mount Sharp western slope",
        "type": "flow",
        "lat": -5.4,
        "lon": 137.8,
        "length_m": 3800,
        "width_m": 900,
        "slope_deg": 11.0,
        "mission": "MRO",
        "region": "Aeolis",
        "features": ["mound", "gully"],
        "description": "夏普山（Aeolis Mons）西坡碎屑流/沟槽。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0028",
        "name": "Jezero western rim slump",
        "type": "slump",
        "lat": 18.4,
        "lon": 77.5,
        "length_m": 2900,
        "width_m": 1500,
        "slope_deg": 27.0,
        "mission": "MRO",
        "region": "Isidis rim",
        "features": ["crater wall"],
        "description": "Jezero 西缘滑塌。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0029",
        "name": "Isidis inner scarp slide",
        "type": "slide",
        "lat": 12.9,
        "lon": 87.0,
        "length_m": 13400,
        "width_m": 6100,
        "slope_deg": 14.5,
        "mission": "MGS",
        "region": "Isidis",
        "features": ["basin scarp"],
        "description": "伊希地盆地内缘滑动。",
        "source_url": "https://pds.nasa.gov/",
    },
    {
        "id": "ls_0030",
        "name": "Lyot crater wall complex",
        "type": "slump",
        "lat": 50.5,
        "lon": 29.3,
        "length_m": 8100,
        "width_m": 4400,
        "slope_deg": 22.5,
        "mission": "MRO",
        "region": "Northern lowlands",
        "features": ["crater wall", "ice-related"],
        "description": "Lyot 坑壁滑塌，北半球中高纬。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0031",
        "name": "Protonilus Mensae lobe",
        "type": "flow",
        "lat": 43.9,
        "lon": 49.0,
        "length_m": 19000,
        "width_m": 4200,
        "slope_deg": 7.5,
        "mission": "MRO",
        "region": "Deuteronilus-Protonilus",
        "features": ["LDA", "glacier-like"],
        "description": "线状谷底沉积/舌状碎屑覆盖，常被归入流动类。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0032",
        "name": "Deuteronilus Mensae apron",
        "type": "flow",
        "lat": 44.7,
        "lon": 23.5,
        "length_m": 21000,
        "width_m": 5000,
        "slope_deg": 6.0,
        "mission": "MGS",
        "region": "Deuteronilus-Protonilus",
        "features": ["LDA"],
        "description": "桌状山周围碎屑裙。",
        "source_url": "https://pds.nasa.gov/",
    },
    {
        "id": "ls_0033",
        "name": "Nilosyrtis Mensae slump",
        "type": "slump",
        "lat": 34.6,
        "lon": 67.8,
        "length_m": 4700,
        "width_m": 2600,
        "slope_deg": 20.0,
        "mission": "MRO",
        "region": "Deuteronilus-Protonilus",
        "features": ["fretted terrain"],
        "description": "斑驳地形陡坎滑塌。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0034",
        "name": "Kasei Valles canyon wall",
        "type": "slide",
        "lat": 24.6,
        "lon": -65.0,
        "length_m": 14800,
        "width_m": 6900,
        "slope_deg": 15.5,
        "mission": "MRO",
        "region": "Kasei Valles",
        "features": ["outflow channel"],
        "description": "卡塞谷谷壁滑动。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0035",
        "name": "Kasei tributary fall",
        "type": "fall",
        "lat": 27.2,
        "lon": -62.4,
        "length_m": 1100,
        "width_m": 420,
        "slope_deg": 37.0,
        "mission": "MRO",
        "region": "Kasei Valles",
        "features": ["channel wall"],
        "description": "支谷陡壁崩落。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0036",
        "name": "Ares Vallis terrace slide",
        "type": "slide",
        "lat": 10.4,
        "lon": -23.0,
        "length_m": 7600,
        "width_m": 3300,
        "slope_deg": 14.0,
        "mission": "Viking",
        "region": "Oxia-Chryse",
        "features": ["outflow channel"],
        "description": "阿瑞斯谷阶地滑动。",
        "source_url": "https://pds.nasa.gov/",
    },
    {
        "id": "ls_0037",
        "name": "Shalbatana Vallis slump",
        "type": "slump",
        "lat": 7.5,
        "lon": -42.5,
        "length_m": 3900,
        "width_m": 2100,
        "slope_deg": 23.5,
        "mission": "MRO",
        "region": "Oxia-Chryse",
        "features": ["channel wall"],
        "description": "沙尔巴塔纳谷壁滑塌。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0038",
        "name": "Valles Marineris pit crater fall",
        "type": "fall",
        "lat": -5.6,
        "lon": -72.9,
        "length_m": 700,
        "width_m": 280,
        "slope_deg": 42.0,
        "mission": "MRO",
        "region": "Valles Marineris",
        "features": ["pit crater"],
        "description": "链坑陡壁崩落。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0039",
        "name": "North polar layered deposit scarp",
        "type": "fall",
        "lat": 83.2,
        "lon": 12.0,
        "length_m": 2600,
        "width_m": 900,
        "slope_deg": 32.0,
        "mission": "MRO",
        "region": "North polar cap",
        "features": ["polar layered deposit"],
        "description": "北极层状沉积物陡坎崩落。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0040",
        "name": "North polar chasma slump",
        "type": "slump",
        "lat": 81.5,
        "lon": -40.0,
        "length_m": 5400,
        "width_m": 2200,
        "slope_deg": 18.0,
        "mission": "MRO",
        "region": "North polar cap",
        "features": ["polar layered deposit", "chasma"],
        "description": "北极裂谷壁滑塌。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0041",
        "name": "South polar layered deposit slide",
        "type": "slide",
        "lat": -82.4,
        "lon": 80.0,
        "length_m": 6100,
        "width_m": 2800,
        "slope_deg": 17.5,
        "mission": "MGS",
        "region": "South polar cap",
        "features": ["polar layered deposit"],
        "description": "南极层状沉积滑动。",
        "source_url": "https://pds.nasa.gov/",
    },
    {
        "id": "ls_0042",
        "name": "Promethei Terra crater slump",
        "type": "slump",
        "lat": -58.3,
        "lon": 90.5,
        "length_m": 4300,
        "width_m": 2000,
        "slope_deg": 24.0,
        "mission": "MRO",
        "region": "Promethei Terra",
        "features": ["crater wall", "ice-related"],
        "description": "南半球高纬撞击坑壁滑塌。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0043",
        "name": "Hellas western rim slide",
        "type": "slide",
        "lat": -35.0,
        "lon": 55.0,
        "length_m": 22600,
        "width_m": 10200,
        "slope_deg": 13.0,
        "mission": "Viking",
        "region": "Hellas",
        "features": ["basin scarp"],
        "description": "希腊盆地西缘大型滑动。",
        "source_url": "https://pds.nasa.gov/",
    },
    {
        "id": "ls_0044",
        "name": "Hellas interior mass wasting",
        "type": "flow",
        "lat": -42.3,
        "lon": 70.4,
        "length_m": 17500,
        "width_m": 4800,
        "slope_deg": 9.0,
        "mission": "MGS",
        "region": "Hellas",
        "features": ["basin floor"],
        "description": "盆地内部物质搬运形成的流舌。",
        "source_url": "https://pds.nasa.gov/",
    },
    {
        "id": "ls_0045",
        "name": "Dao Vallis headwall",
        "type": "slump",
        "lat": -38.1,
        "lon": 93.0,
        "length_m": 8800,
        "width_m": 3600,
        "slope_deg": 21.5,
        "mission": "MRO",
        "region": "Hellas rim",
        "features": ["outflow channel", "headwall"],
        "description": "Dao Vallis 源头滑塌。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0046",
        "name": "Harmakhis Vallis wall slide",
        "type": "slide",
        "lat": -40.6,
        "lon": 90.2,
        "length_m": 9700,
        "width_m": 4100,
        "slope_deg": 16.0,
        "mission": "MRO",
        "region": "Hellas rim",
        "features": ["outflow channel"],
        "description": "Harmakhis 谷壁滑动。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0047",
        "name": "Terra Sirenum crater fall",
        "type": "fall",
        "lat": -39.8,
        "lon": -150.2,
        "length_m": 1300,
        "width_m": 480,
        "slope_deg": 35.0,
        "mission": "MRO",
        "region": "Terra Sirenum",
        "features": ["crater wall"],
        "description": "西宁姆高原撞击坑壁崩落。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0048",
        "name": "Terra Cimmeria gully flow",
        "type": "flow",
        "lat": -39.5,
        "lon": 150.0,
        "length_m": 2800,
        "width_m": 400,
        "slope_deg": 19.0,
        "mission": "MRO",
        "region": "Terra Cimmeria",
        "features": ["gully"],
        "description": "中纬沟槽/碎屑流。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0049",
        "name": "Newton crater wall slump",
        "type": "slump",
        "lat": -40.5,
        "lon": -158.0,
        "length_m": 6100,
        "width_m": 2900,
        "slope_deg": 22.0,
        "mission": "MRO",
        "region": "Terra Sirenum",
        "features": ["crater wall"],
        "description": "Newton 坑壁滑塌。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0050",
        "name": "Gorgonum Chaos mesa slump",
        "type": "slump",
        "lat": -37.3,
        "lon": -170.8,
        "length_m": 3500,
        "width_m": 1700,
        "slope_deg": 20.0,
        "mission": "MGS",
        "region": "Terra Sirenum",
        "features": ["chaos terrain"],
        "description": "混沌地形桌状山滑塌。",
        "source_url": "https://pds.nasa.gov/",
    },
    {
        "id": "ls_0051",
        "name": "Iani Chaos block slide",
        "type": "slide",
        "lat": -2.0,
        "lon": -18.0,
        "length_m": 7200,
        "width_m": 3400,
        "slope_deg": 12.5,
        "mission": "MRO",
        "region": "Oxia-Chryse",
        "features": ["chaos terrain"],
        "description": "Iani Chaos 块体滑动。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0052",
        "name": "Hydraotes Chaos slump",
        "type": "slump",
        "lat": 0.8,
        "lon": -35.5,
        "length_m": 4400,
        "width_m": 2100,
        "slope_deg": 18.0,
        "mission": "MRO",
        "region": "Oxia-Chryse",
        "features": ["chaos terrain"],
        "description": "Hydraotes 混沌区滑塌。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0053",
        "name": "Aureum Chaos fall",
        "type": "fall",
        "lat": -4.4,
        "lon": -27.0,
        "length_m": 950,
        "width_m": 360,
        "slope_deg": 39.0,
        "mission": "MRO",
        "region": "Oxia-Chryse",
        "features": ["chaos terrain", "steep scarp"],
        "description": "Aureum 块体陡崖崩落。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0054",
        "name": "Claritas Fossae graben slide",
        "type": "slide",
        "lat": -31.0,
        "lon": -101.0,
        "length_m": 6800,
        "width_m": 2500,
        "slope_deg": 15.0,
        "mission": "MGS",
        "region": "Tharsis",
        "features": ["graben"],
        "description": "Claritas 地堑壁滑动。",
        "source_url": "https://pds.nasa.gov/",
    },
    {
        "id": "ls_0055",
        "name": "Tempe Terra fault scarp slump",
        "type": "slump",
        "lat": 40.0,
        "lon": -70.0,
        "length_m": 5100,
        "width_m": 2400,
        "slope_deg": 19.5,
        "mission": "MRO",
        "region": "Tempe Terra",
        "features": ["fault scarp"],
        "description": "Tempe 断层陡坎滑塌。",
        "source_url": "https://www.uahirise.org/",
    },
    {
        "id": "ls_0056",
        "name": "Mawrth Vallis layered slump",
        "type": "slump",
        "lat": 24.0,
        "lon": -19.0,
        "length_m": 2700,
        "width_m": 1400,
        "slope_deg": 21.0,
        "mission": "MRO",
        "region": "Oxia-Chryse",
        "features": ["light-toned layer"],
        "description": "Mawrth 层状黏土出露区小型滑塌。",
        "source_url": "https://www.uahirise.org/",
    },
]
