# Generated by Django 5.0.14 on 2026-09-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Landslide",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="编号",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="名称")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("slump", "slump"),
                            ("fall", "fall"),
                            ("flow", "flow"),
                            ("slide", "slide"),
                            ("unknown", "unknown"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="类型",
                    ),
                ),
                ("lat", models.FloatField(verbose_name="纬度")),
                ("lon", models.FloatField(verbose_name="经度")),
                (
                    "length_m",
                    models.FloatField(blank=True, null=True, verbose_name="长度(米)"),
                ),
                (
                    "width_m",
                    models.FloatField(blank=True, null=True, verbose_name="宽度(米)"),
                ),
                (
                    "slope_deg",
                    models.FloatField(blank=True, null=True, verbose_name="坡度(度)"),
                ),
                (
                    "mission",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=64,
                        verbose_name="探测任务",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=64,
                        verbose_name="区域",
                    ),
                ),
                (
                    "features",
                    models.JSONField(blank=True, default=list, verbose_name="地貌特征"),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True, default="", max_length=500, verbose_name="来源"
                    ),
                ),
            ],
            options={
                "db_table": "landslide",
                "ordering": ["id"],
            },
        ),
    ]
